### ISSUE TITLE
RSS Feed

### ISSUE THREAD

**Issue by wezm** [dbanty/dylananthony.com#195]
Any chance you could set [`generate_feed`](https://www.getzola.org/documentation/templates/feeds/) in your Zola config so I can subscribe to your blog?

**Comment by dbanty** [comment]
Hey @wezm I enabled that feature in #196 and added a little RSS icon with a link to the feed at the bottom of the site. Copying that link into Feedly seems to pull up a list of all the content—but I'm not sure if there's supposed to be an easier method that I'm missing 😅.

Could you check out the preview link from the Vercel bot and make sure that the feed is set up in a way that both works for your preferred reader and is easy to consume?
